name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 3306
      DATABASE_HOST: 127.0.0.1
      DATABASE: workout_tracker
      SERVER_PORT: 9000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql.service

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Create Database
        run: |
          mysql -u $DATABASE_USER -p"$DATABASE_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DATABASE;"

      - name: Build
        run: go build -v -o ./workout

      - name: Start Server in Background
        run: |
          ./workout server > /dev/null 2>&1 &
          echo $! > server.pid
          sleep 5

      - name: Health Check
        run: |
          sleep 5  # Give server some time to start
          response=$(curl -v http://localhost:9000/workouttracker/health)
          if [[ "$response" == '{"Status":"Healthy"}' ]]; then
            echo "Server is up, running and healthy!"
          else
            echo "Server is not healthy...."
            
            echo "Printing Server Logs..."
            cat server.log
            
            exit 1
          fi

      - name: Stop Server
        run: |
          kill $(cat server.pid)
  depedancy-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build Dependency-Check from Source
      run: |
        mvn -s settings.xml install -DskipTests=true

    - name: Run Dependency-Check CLI
      run: |
        ./cli/target/release/bin/dependency-check.sh \
          --scan . \
          --out ./dependency-check-report \
          --format HTML,JSON,SARIF
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report/*

  
