name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build -o ./workout 

    - name: Start Server in Background
      run: |
        nohup ./workout server -p 9002 > server.log 2>&1 &
        echo $! > server.pid  # Save the process ID

    - name: Server health status check
      run: |
        sleep 5  # Give server some time to start
        response=$(curl -s http://localhost:9002/wokouttracker/health)
        if [[ "$response" == '{"Status":"Healthy"}' ]]; then
          echo "Server is up, running and healthy!"
        else
          echo "Server is not healthy...."
          exit 1
        fi

    - name: Stop Server
      run: |
        kill $(cat server.pid)
