name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o ./workout ./...

    - name: Start Server in Background
      run: |
        nohup ./workout server -p 9002 > server.log 2>&1 &
        echo $! > server.pid  # Save the process ID

    - name: Run Tests (e.g., curl to check if server is running)
      run: |
        sleep 5  # Give server some time to start
        curl -f http://localhost:9002/wokouttracker/health  # Change to the correct URL or test you need

    - name: Stop Server
      run: |
        kill $(cat server.pid)
