name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 3306
      DATABASE_HOST: 127.0.0.1
      DATABASE: workout_tracker
      SERVER_PORT: 9000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql.service

      - name: install mysql client
        run: |
          sudo apt-get update
          sudo apt-get install -y  mysql-client 

      - name: Create Database
        run: |
          mysql -u $DATABASE_USER -p"$DATABASE_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DATABASE;"

      - name: Build
        run: go build -o ./workout

      - name: Start Server in Background
        run: |
          nohup ./workout server > server.log 2>&1 &
          echo $! > server.pid  # Save the process ID
          
      - name: Server health status check
        run: |
          sleep 5  # Give server some time to start
          response=$(curl -v http://localhost:9000/workouttracker/health)
          if [[ "$response" == '{"Status":"Healthy"}' ]]; then
            echo "Server is up, running and healthy!"
          else
            echo "Server is not healthy...."
            cat server.log
            exit 1
          fi

      - name: Stop Server
        run: |
          kill $(cat server.pid)
