name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 3306
      DATABASE_HOST: 127.0.0.1
      DATABASE: workout_tracker
      SERVER_PORT: 9000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql.service

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Create Database
        run: |
          mysql -u $DATABASE_USER -p"$DATABASE_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DATABASE;"

      - name: Build
        run: go build -v -o ./workout

      - name: Start Server in Background
        run: |
          ./workout server > /dev/null 2>&1 &
          echo $! > server.pid
          sleep 5

      - name: Health Check
        run: |
          curl -f http://0.0.0.0:9000/workouttracker/health

      - name: Stop Server
        run: |
          kill $(cat server.pid)
